version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    entrypoint: ./.docker/entrypoint.sh
    container_name: webhook-service-toolzz
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
      - SERVICE_NAME=webhook-service-toolzz
      - PORT=3000
      - NEW_RELIC_APP_NAME=webhook-service-toolzz

    volumes:
      - .:/home/node/app
